spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch_example
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  flyway:
    baseline-on-migrate: true


